# Generated by Django 5.1.3 on 2025-02-19 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_time_edited", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("edit", "Being edited."),
                            ("submitted", "Submitted and awaiting processing."),
                            ("preparation", "Currently being prepared."),
                            ("delivery", "Currently being delivered."),
                            ("closed", "Delivered and paid."),
                        ],
                        default="edit",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(null=True)),
                (
                    "customer",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="accounts.customer"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                (
                    "discount",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("price", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("are_coupons_used", models.BooleanField(default=False)),
                (
                    "food_portion",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="menu.foodportion"),
                ),
                (
                    "order",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.order"),
                ),
                ("toppings", models.ManyToManyField(to="menu.topping")),
            ],
        ),
    ]
