# Generated by Django 5.1.3 on 2025-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('edit', 'edit'), ('submitted', 'submitted'), ('preparation', 'preparation'), ('delivery', 'delivery'), ('closed', 'closed')], default='edit', max_length=100),
        ),
    ]
