# Generated by Django 5.1.3 on 2025-06-05 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitemrecord',
            name='date_time_edited',
        ),
        migrations.RemoveField(
            model_name='orderitemrecord',
            name='description',
        ),
        migrations.AddField(
            model_name='orderitemrecord',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
