# Generated by Django 5.1.3 on 2025-06-05 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_orderitemrecord_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemrecord",
            name="date_time_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
