# Generated by Django 5.1.3 on 2025-03-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_food_toppings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="foodportion",
            options={"verbose_name_plural": "Food Portions"},
        ),
    ]
