# Generated by Django 5.1.3 on 2025-03-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options_alter_foodportion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodportion',
            options={'verbose_name': 'Food Portion', 'verbose_name_plural': 'Food Portions'},
        ),
    ]
