# Generated by Django 5.1.3 on 2025-08-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_categoryrecord_sizerecord_toppingrecord_foodrecord_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodportion",
            name="is_available",
        ),
    ]
