# Generated by Django 5.1.3 on 2025-02-19 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponreward',
            name='models',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.foodportion'),
        ),
        migrations.AddField(
            model_name='customer',
            name='received_posts',
            field=models.ManyToManyField(to='accounts.newsletterpost'),
        ),
        migrations.AddField(
            model_name='couponreward',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
    ]
