# Generated by Django 5.1.3 on 2025-02-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
