# Generated by Django 5.1.3 on 2025-03-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterpost',
            options={'verbose_name': 'Newsletter Post', 'verbose_name_plural': 'Newsletter Posts'},
        ),
        migrations.AlterModelOptions(
            name='workingday',
            options={'verbose_name': 'Working Day', 'verbose_name_plural': 'Working Days'},
        ),
    ]
