# Generated by Django 5.1.3 on 2025-03-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_newsletterpost_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingday",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
