# Generated by Django 5.1.3 on 2025-03-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_workingday_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workingday",
            old_name="is_closed",
            new_name="is_non_working_day",
        ),
    ]
