# Generated by Django 5.1.3 on 2025-08-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customer_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkingDay',
        ),
    ]
