# Generated by Django 5.1.3 on 2025-06-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='foodportionrecord',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodportionrecord',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitemrecord',
            name='food_portion',
        ),
        migrations.RemoveField(
            model_name='ratingrecord',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orderitemrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitemrecord',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitemtoppingrecord',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitemtoppingrecord',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='orderrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ratingrecord',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CategoryRecord',
        ),
        migrations.DeleteModel(
            name='SizeRecord',
        ),
        migrations.DeleteModel(
            name='FoodPortionRecord',
        ),
        migrations.DeleteModel(
            name='FoodRecord',
        ),
        migrations.DeleteModel(
            name='OrderItemRecord',
        ),
        migrations.DeleteModel(
            name='OrderItemToppingRecord',
        ),
        migrations.DeleteModel(
            name='ToppingRecord',
        ),
        migrations.DeleteModel(
            name='OrderRecord',
        ),
        migrations.DeleteModel(
            name='RatingRecord',
        ),
    ]
